<?php
use App\Enums\UserConfig;

return [
  /**
   * 以下为服务级的错误代码定义
   */
  'ROUTE_CANNOT_FOUND' => array(99997, '访问路由非法，已被系统拦截'),
  'SUCCESS_RESPONSE' => array(200, '数据返回成功'),
  'DEFAULT_ERROR' => array(99999, '服务器错误'),
  'SIGN_ERROR' => array(99998, '无权限使用接口'),
  'ILLEGAL_OPERATION' => array(99989, '用户操作非法，已被系统拦截'),
  /**
   * 以下为用户级的错误代码定义，从10001开始
   */
  'FORM_PARAMS_ERROR' => array(10001, '表单填写错误'),
  'USER_CANNOT_FOUND' => array(20001, '用户无法找到'),
  'PASSWORD_ERROR' => array(20002, '密码错误'),
  'PASSWORD_NOT_SAME_CONFIRMPASSWORD' => array(20003, '两次输入的密码不一致'),
  'VERIFYCODE_NOT_FOUND' => array(20004, '验证码已过期或不存在，请重新生成'),
  'VERIFYCODE_FAILED' => array(20005, '验证码输入错误'),
  'USER_REGISTER_FAILED' => array(20006, '注册失败！'),
  'VERFIYCODE_SEND_FREQUENTLY' => array(20007, '发送过快，请稍后再试'),
  'VERFIYCODE_SEND_FAILED' => array(20008,'验证码发送失败'),
  'LOGIN_STATUS_IS_INVALID' => array(20009, '登录状态失效'),
  'USER_ACCOUNT_IS_LOCKED' => array(20010, '该用户已被管理员禁止登录'),
  'AUTHOR_CANNOT_CHANGE_NICKNAME' => array(20011, '您已经是作者啦,无法修改昵称了哦~'),
  'CHANGE_PASSWORD_IS_FAILED' => array(20012, '修改密码失败'),
  'CHANGE_USER_INFO_IS_FAILED' => array(20013, '修改用户信息失败'),
  'DENY_ALLOW_THIS_ACCOUNT_TYPE' => array(20016, '此登录方式不被允许'),
  'USER_NICKNAME_IS_EXIST' => array(20017, '用户昵称已经存在'),
  'SIGNED_AUTHOR_CANNOT_CHANGE_USER_NICKNAME' => array(20018, '签约作者无法修改昵称哦~'),
  'USER_COMMENT_OR_BOARD_AUTH_BANNED' => array(20020, '您暂时无法完成此操作'),
  'BOARD_IS_OFF' => array(22001, '此版块已关闭'),
  'TOPIC_IS_DELETED' => array(23001, '此主题已被删除'),
  'NOTICE_IS_DELETED' => array(24001, '公告数据无法找到'),
  'REPLY_TO_FAST' => array(23002, '回帖过快，请稍后再试'),
  'CLASS_NOT_FOUND' => array(25001, '分类数据无法查询到'),
  'BOOK_NOT_FOUND' => array(26001, '作品无法找到'),
  'DENY_ALLOW_MANAGE_THIS_BOOK' => array(26002, '您无权管理此作品'),
  'TAG_DOES_NOT_MEET_THE_RULE' => array(26003, 'TAG不符合规则'),
  'BOOK_IS_SIGNED' => array(26004, '作品已经签约了'),
  'BOOK_HAVE_ALREADY_APPLIED_SIGN' => array(26005, '作品已经申请签约了'),
  'BOOK_CNT_FEW' => array(26006, '对不起，您还未到申请签约的条件，请继续加油!'),
  'BOOK_EXTEND_DENY_ALLOW' => array(26007, '原创性/时空/视角不在选择范围内，请检查'),
  'SECTION_NOT_FOUND' => array(27001, '分卷数据无法找到'),
  'SECTION_DATA_ERROR' => array(27002, '分卷数据错误'),
  'ACCOUNT_RESPONSE_NOT_NULL' => array(20014, '用户资源不为空'),
  'USER_BOOK_NOT_NULL' => array(20015, '用户尚有未删除的书籍，请联系管理员'),
  'CHANGE_USER_INFO_MODIFY_TIME_LIMIT_DID_NOT_ARRIVE' => array(20019, '未到下一次可修改用户信息的时间~'),
  'CHAPTER_NOT_FOUND' => array(28001, '章节信息无法找到'),
  'FATHER_COMMENT_NOT_FOUND' => array(29001, '父评论信息无法找到'),
  'COMMENT_PARAM_MISSING' => array(29002, '评论参数缺失'),
  'SECTION_HAS_CHAPTER' => array(27003, '分卷下有章节数据，请先移动章节分卷'),
  'PUBLISHTIME_FAILED_MIN' => array(28002, '存稿时间过小'),
  'PUBLISHTIME_FAILED_MAX' => array(28003, '存稿发表时间间隔过大'),
  'PUBLISHTIME_LESS_THAN_FIFTEEN_MINUTES' => array(28004, '存稿设定时间小于当前5分钟，已不可更改'),
  'DENY_ALLOW_MANAGE_THIS_CHAPTER' => array(28005, '您无法管理此章节'),
  'CHAPTER_VIP_NOT_BUY' => array(28006, 'VIP章节尚未购买'),
  'ACCESS_CHAPTER_VIP_NEED_LOGIN' => array(28007, '阅读VIP必须先登录'),
  'IMPOSSIBLE_TO_BUY_VIP_CHAPTER' => array(28008, '无法完成此次购买'),
  'BUY_VIP_CHAPTER_GOLD_INSUFFICIENT' => array(28009, UserConfig::GoldName.'不足，无法购买VIP章节'),
  'CANNOT_CHANGE_THIS_SECTION' => array(27004, '此分卷禁止修改'),
  'SIGNIN_ILLEGAL' => array(30001, '签到行为不合法'),
  'SIGNIN_ERROR' => array(30002, '签到失败!原因是数据库出现了问题'),
  'CANNOT_SIGN_IN_REPEATEDLY' => array(30003, '您今日已经签到过了'),
  'BOOK_NOT_SIGN_CANNOT_GIFT' => array(31001, '作品尚未签约，无法送礼'), 
  'GIFT_GOLD_INSUFFICIENT' => array(31002, UserConfig::GoldName.'不足，无法完成送礼'),
  'TICKET_COUNT_INSUFFICIENT' => array(31003, '票（道具）不足'),
  'TICKET_COUNT_CURREMT_MAX' => array(31004, '当前投票已达最大值'),
  'SIGNSTATUS_ABNORMAL' => array(32001, '作品签约状态异常(已过期或尚未签约)'),
  'AUTHOR_IDENTITY_INVALID' => array(33001, '作者身份验证失败'),
  'UPGRADE_AUHTOR_FAILED' => array(33002, '升级作者失败'),
  'SIGNED_AUTHOR_CAN_NOT_CHANGE_INFO' => array(33003, '签约作者不能修改作者信息哦，请联系您的责任编辑'),
  'AUTHOR_BANK_INFO_CANNOT_CHANGE' => array(33004, '为安全起见，设定支付信息后无法二次修改，如需修改，请联系网站管理员'),
  'PAY_PROGRAM_NOT_FOUND' => array(34001, '充值方案不合法'),
  'PAY_CHANNEL_ILLEGAL' => array(35001, '充值渠道不合法'),
  'WEBVIEW_AROUSE_FAILED' => array(35002, '支付页面唤起失败'),
  'ORDER_NOT_GENERATED' => array(35003, '订单未生成或已经失效'),
  'ORDER_VERIFY_FAILED' => array(35004, '订单信息校验失败'),
  'GENERATE_ORDER_COUNT_EXCEED_THE_LIMIT' => array(35005, '生成订单数量超出限制'),
  'ORDER_GENERATE_FAILED' => array(35006, '订单生成失败，请联系管理员'), 
  'UPLOAD_FILE_ILLEGAL' => array(36001, '图片上传不合法'),
  'USER_NOT_AUTH_CREATE_BOOK_LIST' => array(37001, '您暂时无法上传书单'),
  'BOOK_LIST_DATA_NOT_FOUND' => array(37002, '书单不存在'), 
  'DENY_ALLOW_MANAGE_BOOK_LIST' => array(37003, '无权管理此书单'),
  'BOOK_LIST_DATA_MAX_LIMIT' => array(37004, '每个书单最多添加100本书籍'),
  'BOOK_ID_LIST_NOT_ARRAY' => array(37005, '数据错误，添加书籍失败'),
  'A_REQUEST_JUST_ADD_TEN_BOOK' => array(37006, '每次最多请只添加10本书籍'),
  'REPEAT_FOCUS_ON_BOOK_LIST' => array(37007, '不可以重复关注书单哦'),
  'DENY_DELETE_THIS_FOCUS_ON_RECORD' => array(37008, '无法删除此关注记录'),
  'YOU_HAVE_LIKED' => array(38001, '您已经点过赞了'),
  'BOOK_SHELF_SELF_COUNT_LIMIT' => array(39001, '自定义书架超出当前等级限制'),
  'USER_GROUP_NOT_FOUND' => array(20020, '用户组无法找到'),
  /**
   * 以下为管理员操作的 Error Code，Code以 500xxxx的形式来定义
   */
  'ADMIN_NOTICE_CANNOT_NULL' => array(5000001, '公告ID不得为空'),
  'ADMIN_NOTICE_NOT_FOUND' => array(5000002, '公告无法找到'),
  'ADMIN_CAN_NOT_ADD_RECOMMEND_TO_THIS_BOOK' => array(5000003, '本作品无法添加作品推荐'),
  'RECOMMEND_INFO_NOT_FOUND' => array(5000004, '此推荐榜单不存在'),
  'RECOMMEND_NOT_FOUND' => array(5000005, '此推荐数据不存在'),
  'RECOMMEND_COUNT_MAX' => array(5000006, '此榜单数量已达上限，请先删除一些推荐数据吧~'),
  'DENY_ALLOW_THIS_SEARCH_FIELD' => array(5000007, '不允许使用此搜素方法'),
  'BOOK_DATA_NOT_FOUND' => array(5000008, '作品数据无法找到'),
  'PUBLISHSTATUS_CHANGE_FAILED' => array(5000009, '作品状态修改失败'),
  'CLASS_DATA_NOT_FOUND' => array(5000010, '分类信息无法找到'),
  'USER_DATA_NOT_FOUND' => array(5000011, '用户信息无法找到'),
  'USER_INFO_CHANGE_FAILED' => array(5000012, '用户信息修改失败'),
  'CHAPTER_INFO_NOT_FOUND' => array(5000013, '章节信息无法找到'),
  'BOOK_SECTION_INFO_FALSE' => array(5000014, '卷信息错误'),
  'CHAPTER_INFO_CHANGE_FAILED' => array(5000015, '章节内容修改失败'),
  'CHAPTER_IS_NOT_TEMP' => array(5000016, '此章节并非草稿'),
  'PILIANG_MODULE_ID_DENY_ALLOW' => array(5000017, '此操作不被允许[批量]'),
  'PILIANG_CHAPTER_LIST_INFO_CHANGE_FAILED' => array(5000018, '章节信息修改失败[批量]'),
  'TOPIC_DATA_NOT_FOUND' => array(5000019, '主题贴信息无法找到'),
  'REPLY_DATA_NOT_FOUND' => array(5000020, '回帖信息无法找到'),
  'BBS_MODULE_NAME_DENY_ALLOW' => array(5000021, '此操作不被允许'),
  'DATA_UPDATE_FAILED' => array(5000022, '数据更新失败'),
  'CAN_NOT_FOUND_THIS_APPLY_INFO' => array(5000023, '无法找到此申请信息'),
  'THIS_APPLY_INFO_PROCESSED' => array(5000024, '此签约信息已经处理过了'),
  'ADMIN_BOOK_IS_SIGNED' => array(5000025, '作品已经签约，不能重复签约'),
  'AUTHOR_INFO_IMPERFECT' => array(5000026, '请先要求作者完善个人信息'),
  'BOOK_SIGN_STATUS_ABOLISHED' => array(5000027, '作品签约状态已经为解约状态'),
  'CHANGE_AUTHOR_INFO_MODULE_NAME_DENY_ALLOW' => array(5000028, '此操作不被允许'),
  'COMMENT_SEARCH_MODULE_ID_DENY_ALLOW' => array(5000029, '筛选出错'),
  'COMMENT_HAS_BEEN_DELETED' => array(5000030, '评论已经被删除'),
  'COMMENT_STATUS_NORMAL' => array(5000031, '评论未被删除，不需要恢复'),
  'THIS_ACCOUNT_IS_LOCKED' => array(5000032, '此帐号状态异常，无法锁定'),
  'THIS_TIMESTAMP_NOT_IN_BAN_TIME_ALLOW_LIST' => array(5000033, '请在允许范围内关闭用户权限'),
  'USER_ID_LIST_NOT_A_LIST' => array(5000034, '传入用户出错'),
  'NOTIFY_CANNOT_FOUND' => array(5000035, '无法找到此通知'),
  'QD_CHANNEL_NOT_FOUND' => array(5000036, '渠道不存在'),
  'QD_CHANNEL_CLASS_MAP_NOT_FOUND' => array(5000037, '渠道分类映射不存在'),
  'AUTHORINFO_CANNOT_FOUND' => array(5000038, '作者信息无法找到，请先要求作者创建信息才可获得'),
  'DENY_ALLOW_TICKET_NAME' => array(5000039, '不被允许的道具名称'),
  'ADMIN_AUTH_CHECK_FAILED' => array(5000040, '管理员权限鉴定失败'),
  'ADMIN_CENTER_ORDER_NOT_FOUND' => array(5000041, '订单信息无法找到'),
  'ADMIN_CENTER_ORDER_PROCESSED' => array(5000042, '订单已经处理完毕，请勿二次处理'),
];